//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeukonstChecklistLibDb
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auftragsknoten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Auftragsknoten()
        {
            this.AuftragsknotenCheckpoints = new HashSet<Checkpoint>();
        }
    
        public int Id { get; set; }
        public string KnotenID { get; set; }
        public int Sachnummer { get; set; }
        public bool Freigabe { get; set; }
        public int UserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Checkpoint> AuftragsknotenCheckpoints { get; set; }
        public virtual User VonUser { get; set; }
    }
}
